name: GD-Posix-Apps Build/test CI
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  posix-build:
    name: Build and test on ${{ matrix.os }} - extensions enabled - ${{matrix.extensions}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        extensions: [OFF, ON]

    steps:
    - uses: actions/checkout@v2
    - name: Packed install (Ubuntu)
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        sudo apt install ninja-build
    - name: Packed install (Ubuntu)
      if: ${{ matrix.os }} == "macos-latest"
      run: |
        brew install ninja
    - name: Configure
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/build"
        cmake -S "${GITHUB_WORKSPACE}" -B "${GITHUB_WORKSPACE}/build" -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DENABLE_NON_POSIX_EXTENSIONS:BOOL=${{matrix.extensions}}
    - name: Build
      run: cmake --build "${GITHUB_WORKSPACE}/build" --config Release
    - name: Test
      run: |
        cd "${GITHUB_WORKSPACE}/build"
        ctest


  windows-build:
    name: Build and test on ${{ matrix.os }} - extensions enabled - ${{matrix.extensions}}
    runs-on: ${{ matrix. os }}
    strategy:
      matrix:
        os: [windows-latest]
        extensions: [0, 1]

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        cmake -S "$Env:GITHUB_WORKSPACE" -B "$Env:GITHUB_WORKSPACE\\build" -DCMAKE_BUILD_TYPE:STRING=Release -DENABLE_NON_POSIX_EXTENSIONS:BOOL=${{matrix.extensions}}
    - name: Build
      run: cmake --build "$Env:GITHUB_WORKSPACE\\build" --config Release
    - name: Test
      run: cmake --build "$Env:GITHUB_WORKSPACE\\build" --config Release  --target RUN_TESTS

